import type { FamilyStore, Person, SourceRecord } from "./types";

const id = (prefix: string) => `${prefix}-${crypto.randomUUID().slice(0, 8)}`;

export const makeId = (prefix = "person") => id(prefix);

export const makeEventId = () => id("event");

export const makeSourceId = () => id("source");

export const makeMemoryId = () => id("memory");

export const seedSources: SourceRecord[] = [
  {
    id: "s-household-book",
    title: "Nguyen household registration book",
    type: "record",
    url: "",
    note: "Scanned household book used for elder birth dates and family links.",
    confidence: "confirmed",
    linkedPersonIds: ["p-hoa", "p-lan", "p-minh", "p-mai"],
    addedAt: "2026-04-10T00:00:00.000Z",
  },
  {
    id: "s-anna-interview",
    title: "Anna oral-history interview with Hoa",
    type: "interview",
    url: "",
    note: "Interview notes about the Da Nang branch and old reunion photos.",
    confidence: "likely",
    linkedPersonIds: ["p-hoa", "p-anna", "p-linh"],
    addedAt: "2026-04-18T00:00:00.000Z",
  },
  {
    id: "s-lan-clinic-note",
    title: "Lan clinic follow-up note",
    type: "document",
    url: "",
    note: "Private health follow-up note. Keep visible only to trusted family members.",
    confidence: "confirmed",
    linkedPersonIds: ["p-lan"],
    addedAt: "2026-04-21T00:00:00.000Z",
  },
];

export const seedPeople: Person[] = [
  {
    id: "p-hoa",
    givenName: "Hoa",
    familyName: "Nguyen",
    nickname: "Grandpa Hoa",
    gender: "male",
    birthDate: "1942-03-18",
    deathDate: "",
    location: "Da Nang, Vietnam",
    occupation: "Retired teacher",
    vitalStatus: "living",
    wellbeing: "stable",
    contactState: "active",
    privacy: "family",
    tags: ["elder", "source-holder"],
    notes: "Keeps family stories and old photographs.",
    parents: [],
    partners: ["p-lan"],
    children: ["p-minh", "p-mai"],
    sourceIds: ["s-household-book", "s-anna-interview"],
    memories: [
      {
        id: "m-hoa-reunion",
        title: "Tet reunion story",
        type: "story",
        url: "",
        date: "2024-02-10",
        note: "Hoa identified relatives in the reunion photos and described the old family home.",
        privacy: "family",
      },
    ],
    events: [
      {
        id: "e-hoa-birth",
        date: "1942-03-18",
        type: "birth",
        title: "Born in Quang Nam",
        note: "Birth date confirmed by household record.",
        location: "Quang Nam, Vietnam",
        confidence: "confirmed",
      },
      {
        id: "e-hoa-status",
        date: "2026-04-15",
        type: "status",
        title: "Stable and active",
        note: "Walks every morning and helps identify relatives in photos.",
        location: "Da Nang, Vietnam",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-lan",
    givenName: "Lan",
    familyName: "Tran",
    nickname: "Grandma Lan",
    gender: "female",
    birthDate: "1946-08-09",
    deathDate: "",
    location: "Da Nang, Vietnam",
    occupation: "Textile merchant",
    vitalStatus: "living",
    wellbeing: "needs-attention",
    contactState: "active",
    privacy: "private",
    tags: ["elder", "health-watch"],
    notes: "Family checks in twice a week.",
    parents: [],
    partners: ["p-hoa"],
    children: ["p-minh", "p-mai"],
    sourceIds: ["s-household-book", "s-lan-clinic-note"],
    memories: [],
    events: [
      {
        id: "e-lan-birth",
        date: "1946-08-09",
        type: "birth",
        title: "Born in Hue",
        note: "Date from family bible.",
        location: "Hue, Vietnam",
        confidence: "likely",
      },
      {
        id: "e-lan-health",
        date: "2026-04-20",
        type: "health",
        title: "Needs appointment follow-up",
        note: "Blood pressure check scheduled with her clinic.",
        location: "Da Nang, Vietnam",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-minh",
    givenName: "Minh",
    familyName: "Nguyen",
    gender: "male",
    birthDate: "1970-01-21",
    deathDate: "",
    location: "Seoul, South Korea",
    occupation: "Engineer",
    vitalStatus: "living",
    wellbeing: "thriving",
    contactState: "active",
    privacy: "shared",
    tags: ["immigration", "documents"],
    notes: "Maintains scanned identity records.",
    parents: ["p-hoa", "p-lan"],
    partners: ["p-sora"],
    children: ["p-anna", "p-jun"],
    sourceIds: ["s-household-book"],
    memories: [],
    events: [
      {
        id: "e-minh-move",
        date: "2002-09-05",
        type: "move",
        title: "Moved to Seoul",
        note: "Moved for a long-term engineering role.",
        location: "Seoul, South Korea",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-sora",
    givenName: "Sora",
    familyName: "Kim",
    gender: "female",
    birthDate: "1973-06-14",
    deathDate: "",
    location: "Seoul, South Korea",
    occupation: "Nurse",
    vitalStatus: "living",
    wellbeing: "stable",
    contactState: "active",
    privacy: "shared",
    tags: ["caregiver"],
    notes: "Coordinates elder care visits.",
    parents: [],
    partners: ["p-minh"],
    children: ["p-anna", "p-jun"],
    sourceIds: [],
    memories: [],
    events: [
      {
        id: "e-sora-career",
        date: "1996-03-01",
        type: "career",
        title: "Started nursing career",
        note: "First hospital appointment.",
        location: "Busan, South Korea",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-mai",
    givenName: "Mai",
    familyName: "Nguyen",
    gender: "female",
    birthDate: "1975-11-02",
    deathDate: "",
    location: "Ho Chi Minh City, Vietnam",
    occupation: "Restaurant owner",
    vitalStatus: "living",
    wellbeing: "stable",
    contactState: "infrequent",
    privacy: "family",
    tags: ["branch-lead"],
    notes: "Primary contact for the southern branch.",
    parents: ["p-hoa", "p-lan"],
    partners: [],
    children: ["p-linh"],
    sourceIds: ["s-household-book"],
    memories: [],
    events: [
      {
        id: "e-mai-career",
        date: "2010-10-10",
        type: "career",
        title: "Opened restaurant",
        note: "Business became the local meeting place for relatives.",
        location: "Ho Chi Minh City, Vietnam",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-anna",
    givenName: "Anna",
    familyName: "Nguyen",
    gender: "female",
    birthDate: "2004-12-22",
    deathDate: "",
    location: "Seoul, South Korea",
    occupation: "Student",
    vitalStatus: "living",
    wellbeing: "thriving",
    contactState: "active",
    privacy: "shared",
    tags: ["student"],
    notes: "Interested in collecting oral histories.",
    parents: ["p-minh", "p-sora"],
    partners: [],
    children: [],
    sourceIds: ["s-anna-interview"],
    memories: [],
    events: [
      {
        id: "e-anna-education",
        date: "2025-09-01",
        type: "education",
        title: "Started university",
        note: "Studying design and archiving.",
        location: "Seoul, South Korea",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-jun",
    givenName: "Jun",
    familyName: "Nguyen",
    gender: "male",
    birthDate: "2009-04-30",
    deathDate: "",
    location: "Seoul, South Korea",
    occupation: "Student",
    vitalStatus: "living",
    wellbeing: "stable",
    contactState: "active",
    privacy: "private",
    tags: ["minor"],
    notes: "Private profile.",
    parents: ["p-minh", "p-sora"],
    partners: [],
    children: [],
    sourceIds: [],
    memories: [],
    events: [
      {
        id: "e-jun-status",
        date: "2026-05-01",
        type: "status",
        title: "School year updated",
        note: "Moved up one grade.",
        location: "Seoul, South Korea",
        confidence: "confirmed",
      },
    ],
  },
  {
    id: "p-linh",
    givenName: "Linh",
    familyName: "Pham",
    gender: "nonbinary",
    birthDate: "2001-07-17",
    deathDate: "",
    location: "Ho Chi Minh City, Vietnam",
    occupation: "Photographer",
    vitalStatus: "living",
    wellbeing: "unknown",
    contactState: "infrequent",
    privacy: "family",
    tags: ["photos", "needs-update"],
    notes: "Profile needs a recent check-in.",
    parents: ["p-mai"],
    partners: [],
    children: [],
    sourceIds: ["s-anna-interview"],
    memories: [
      {
        id: "m-linh-photos",
        title: "Tet reunion photo folder",
        type: "photo",
        url: "",
        date: "2024-02-10",
        note: "Placeholder for the external photo folder or archive location.",
        privacy: "family",
      },
    ],
    events: [
      {
        id: "e-linh-memory",
        date: "2024-02-10",
        type: "memory",
        title: "Uploaded reunion photos",
        note: "Shared a folder of Tet reunion images.",
        location: "Ho Chi Minh City, Vietnam",
        confidence: "confirmed",
      },
    ],
  },
];

export const seedStore: FamilyStore = {
  people: seedPeople,
  sources: seedSources,
  selectedPersonId: "p-lan",
  updatedAt: new Date().toISOString(),
};
